services:
  stationeers-server:
    container_name: stationeers-server
    build : .
    image: stationeers-server-ui:latest
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
        reservations:
          cpus: '4'
          memory: 8G
    ports:
      - "8443:8443"
      - "27016:27016/udp"
      - "27016:27016/tcp"
      - "27015:27015/udp"
      - "27015:27015/tcp"
    volumes:
      # Persist app data between container restarts
      - app-data:/app
      # Mount saves and config for easy access/editing outside the container
      - ./saves:/app/saves:rw
      - ./UIMod/config:/app/UIMod/config:rw
      - ./UIMod/tls:/app/UIMod/tls:rw
    restart: unless-stopped
    command: []

volumes:
  app-data: