<script>
  import { onMount } from 'svelte';
  import { apiFetch, hasPermission } from '../../services/api-v7';
  import { notify } from '../../services/activity';

  let backups=$state([]), status=$state(null), loading=$state(true), busy=$state(''), mode=$state('tar'), selected=$state(null);
  onMount(()=>{load();const timer=setInterval(load,20000);return()=>clearInterval(timer);});
  async function request(path,options){const response=await apiFetch(path,options);const body=await response.json().catch(()=>({}));if(!response.ok||body.success===false)throw new Error(body?.error?.message||body.message||`Request failed (${response.status})`);return body;}
  async function load(){try{const [list,state]=await Promise.all([request('/api/v3/backup/list'),request('/api/v3/backup/status')]);backups=(list.data?.backups||list.backups||[]).map(item=>typeof item==='string'?{id:item,name:item}:item);status=state.data||state;}catch(error){notify('Could not load backups','error',error.message);}finally{loading=false;}}
  async function create(){busy='create';try{await request('/api/v3/backup/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode})});notify('Backup started','success',mode==='tar'?'Compressed archive':'Full snapshot');await load();}catch(error){notify('Backup failed','error',error.message);}finally{busy='';}}
  async function restore(){
    if(!selected||!window.confirm(`Restore ${selected.name||selected.id}? The running server should be stopped.`))return;
    busy='restore';try{await request('/api/v3/backup/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({backupName:selected.name||selected.id,skipPreBackup:false})});notify('Restore completed','success',selected.name||selected.id);selected=null;await load();}catch(error){notify('Restore failed','error',error.message);}finally{busy='';}
  }
  function details(item){if(item.createdAt)return new Date(item.createdAt).toLocaleString();const match=(item.name||'').match(/(\d{4}-\d{2}-\d{2})_(\d{2}-\d{2}-\d{2})/);return match?`${match[1]} ${match[2].replaceAll('-',':')}`:'Date unavailable';}
  function size(item){if(!item.sizeBytes)return 'Size unavailable';const units=['B','KB','MB','GB'];let value=item.sizeBytes,index=0;while(value>1024&&index<3){value/=1024;index++;}return `${value.toFixed(index?1:0)} ${units[index]}`;}
</script>

<section class="backup-workspace">
  <article class="backup-status surface"><div class="status-orb" class:ready={status?.systemReady} class:busy={status?.isRunning}></div><div><span class="eyebrow">Backup engine</span><h2>{loading?'Checking…':status?.isRunning?'Backup in progress':status?.systemReady?'Ready to protect':'Needs configuration'}</h2><p>{status?.isLoopRunning?'Automatic scheduling is active.':'Automatic scheduling is currently inactive.'}</p></div>{#if hasPermission('backups.create')}<div class="create"><select bind:value={mode}><option value="tar">Compressed archive</option><option value="copy">Full snapshot</option></select><button onclick={create} disabled={!!busy||!status?.systemReady}>{busy==='create'?'Starting…':'Create backup'}</button></div>{/if}</article>

  <div class="backup-body surface">
    <header><div><span class="eyebrow">Restore points</span><h3>{backups.length} available</h3></div><button onclick={load} disabled={loading}>Refresh</button></header>
    {#if !backups.length&&!loading}<div class="empty-state"><span class="eyebrow">No restore points</span><h2>Create the first backup</h2><p>Backups will appear here with their creation time and format.</p></div>
    {:else}<div class="backup-list">{#each backups as item (item.id||item.name)}<button class="backup-row" class:selected={selected==item} onclick={()=>selected=item}><span class="archive-mark"></span><span><strong>{item.name||item.id}</strong><small>{details(item)}</small></span><span><strong>{size(item)}</strong><small>{item.format||((item.name||'').endsWith('.gz')?'TAR archive':'Snapshot')}</small></span><span class="select-mark">{selected==item?'Selected':'Select'}</span></button>{/each}</div>{/if}
    {#if selected&&hasPermission('backups.restore')}<footer><div><strong>Restore {selected.name||selected.id}</strong><small>A safety backup will be created first.</small></div><button class="restore" onclick={restore} disabled={!!busy}>{busy==='restore'?'Restoring…':'Restore selected'}</button></footer>{/if}
  </div>
</section>

<style>
  .backup-workspace{display:grid;gap:16px}.backup-status{display:grid;grid-template-columns:52px 1fr auto;align-items:center;gap:18px;padding:25px}.status-orb{width:48px;height:48px;border-radius:50%;background:var(--text-danger);box-shadow:0 0 24px color-mix(in srgb,var(--text-danger) 35%,transparent)}.status-orb.ready{background:var(--text-success);box-shadow:0 0 28px color-mix(in srgb,var(--text-success) 42%,transparent)}.status-orb.busy{background:var(--text-warning);animation:pulse 1.2s infinite}.backup-status h2{margin:4px 0}.backup-status p{color:var(--text-secondary);margin:0}.create{display:flex;gap:8px}.create button{background:linear-gradient(135deg,var(--accent-primary),var(--accent-secondary));color:#07101d;border:0;font-weight:800}.backup-body{overflow:hidden}.backup-body>header,.backup-body>footer{display:flex;align-items:center;justify-content:space-between;padding:20px 22px}.backup-body>header{border-bottom:1px solid var(--border-color)}.backup-body h3{margin:4px 0 0}.backup-list{display:grid}.backup-row{display:grid;grid-template-columns:42px minmax(0,1fr) 150px 80px;align-items:center;gap:14px;text-align:left;padding:15px 22px;border:0;border-bottom:1px solid var(--border-color);border-radius:0;background:transparent}.backup-row.selected{background:var(--bg-active)}.backup-row strong,.backup-row small{display:block}.backup-row small{color:var(--text-muted);margin-top:3px}.archive-mark{width:38px;height:38px;border-radius:12px;background:linear-gradient(135deg,var(--bg-active),color-mix(in srgb,var(--accent-secondary) 20%,transparent));border:1px solid var(--border-color)}.select-mark{color:var(--text-accent);font-size:.72rem}.backup-body>footer{border-top:1px solid var(--border-color);background:var(--bg-secondary)}.backup-body>footer small{display:block;color:var(--text-secondary);margin-top:3px}.restore{color:var(--text-warning);border-color:color-mix(in srgb,var(--text-warning) 35%,transparent)}@keyframes pulse{50%{opacity:.5;transform:scale(.94)}}@media(max-width:900px){.backup-status{grid-template-columns:44px 1fr}.create{grid-column:1/-1}.create>*{flex:1}.backup-row{grid-template-columns:36px 1fr}.backup-row>span:nth-child(3),.backup-row>span:nth-child(4){display:none}}
</style>
