name: Build and Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-release:
    # Only run if the PR was merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for creating releases

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Compile the build.go script to produce Executable
      - name: Run ./build/build.go
        run: go run ./build/build.go

      # Verify the executable exists
      - name: Verify build output
        run: |
          cd build
          if ls StationeersServerControl*; then
            echo "Build succeeded: Executable found."
          else
            echo "Build failed: No executable found."
            exit 1
          fi

      # Check for git tag and set output
      - name: Check for git tag
        id: check_tag
        run: |
          # Get tags associated with the merged commit
          TAG=$(git tag --points-at ${{ github.sha }})
          if [ -n "$TAG" ]; then
            echo "Found tag: $TAG"
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          else
            echo "No tag found for this commit."
            echo "tag=" >> $GITHUB_OUTPUT
          fi

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        if: steps.check_tag.outputs.tag != ''
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        if: steps.check_tag.outputs.tag != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        if: steps.check_tag.outputs.tag != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ssui:${{ steps.check_tag.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/ssui:latest

      # Create release (not prerelease) if tag exists
      - name: Create Release
        if: steps.check_tag.outputs.tag != ''
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          tag_name: ${{ steps.check_tag.outputs.tag }}
          name: "Release ${{ steps.check_tag.outputs.tag }}"
          files: ./build/StationeersServerControl*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
