name: PR Container Smoke Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  smoke:
    name: Smoke (Container ${{ matrix.distro }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu
            image: ubuntu:24.04
            pkg_update: apt-get update
            install: apt-get install -y --no-install-recommends ca-certificates curl git build-essential wget nodejs npm bash
            needs_go: true
          - distro: debian
            image: debian:trixie
            pkg_update: apt-get update
            install: apt-get install -y --no-install-recommends ca-certificates curl git build-essential wget nodejs npm bash
            needs_go: true
          - distro: arch
            image: archlinux:base
            pkg_update: pacman -Sy --noconfirm
            install: pacman -S --noconfirm ca-certificates curl git wget tar nodejs npm go base-devel bash
            needs_go: false
    container:
      image: ${{ matrix.image }}
    env:
      CGO_ENABLED: 0
    steps:
      - name: Prepare packages
        run: |
          set -e
          ${{ matrix.pkg_update }}
          ${{ matrix.install }}
      - name: Install Go (if needed)
        if: matrix.needs_go == true
        run: |
          set -e
          ARCH=$(uname -m)
          case "$ARCH" in
            x86_64) GOARCH=amd64 ;;
            aarch64) GOARCH=arm64 ;;
            *) echo "Unsupported arch: $ARCH"; exit 1 ;;
          esac
          curl -fsSL https://go.dev/dl/go${GO_VERSION}.linux-${GOARCH}.tar.gz -o /tmp/go.tgz
          rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go.tgz
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          /usr/local/go/bin/go version
      - name: Verify Go (preinstalled)
        if: matrix.needs_go == false
        run: go version || which go || true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node version
        run: node --version && npm --version || true
      - name: Install frontend deps
        working-directory: frontend
        run: |
          if [ -f package.json ]; then npm ci || npm install; fi
      - name: Build frontend
        working-directory: frontend
        run: |
          if [ -f package.json ]; then npm run build || echo 'frontend build failed (continuing)'; fi
      - name: Run smoke test
        run: bash ./.github/scripts/run-smoke.sh
      - name: Collect results
        if: always()
        id: collect
        run: |
          echo "status=$(cat smoke-logs/result.txt 2>/dev/null || echo 'missing')" >> $GITHUB_OUTPUT
          echo "status_json=$(cat smoke-logs/status.json 2>/dev/null || echo '{}')" >> $GITHUB_OUTPUT
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: smoke-${{ matrix.distro }}
            path: |
              smoke-logs/server.log
              smoke-logs/status.json
              smoke-logs/result.txt
            if-no-files-found: warn
